name: Flight Delay CI/CD Pipeline

on:
  workflow_dispatch:

concurrency:
  group: flight-delay-pipeline
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Flight Delay Pipeline
    runs-on: ubuntu-latest

    steps:

    ############################################################
    # Checkout Repository
    ############################################################

    - name: Checkout Repository
      uses: actions/checkout@v4

    ############################################################
    # Setup Python
    ############################################################

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    ############################################################
    # Configure AWS Credentials
    ############################################################

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    ############################################################
    # Setup Terraform
    ############################################################

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    ############################################################
      # Install Test Dependencies
    ############################################################

    - name: Install Test Dependencies
      run: |
          python -m pip install --upgrade pip
          pip install pytest pyspark black flake8 boto3

    ############################################################
    # Run Unit Tests
    ############################################################

    - name: Run Unit Tests
      env:
        PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/glue/silver_to_gold
      run: |
        pytest tests -v
        
    ############################################################
     # Check Code Formatting
    ############################################################

    - name: Check Code Formatting
      run: |
        black --check glue tests

    ############################################################
      # Run Flake8
    ############################################################

    - name: Run Flake8
      run: |
        flake8 \
          --max-line-length=88 \
          --extend-ignore=E203,W503 \
          glue tests
    ############################################################
    # Create Bronze Dependency ZIP
    ############################################################

    - name: Create Bronze Dependency ZIP
      run: |
        cd glue/bronze_to_silver
        zip -r dependencies.zip \
          config.py \
          utils.py

    ############################################################
    # Create Silver Dependency ZIP
    ############################################################

    - name: Create Silver Dependency ZIP
      run: |
        cd glue/silver_to_gold
        zip -r silver_to_gold_lib.zip \
          config.py \
          constants.py \
          dimensions.py \
          ml_dataset.py \
          spark_setup.py \
          transformations.py \
          validation.py \
          visualization.py \
          writers.py

    ############################################################
    # Upload Bronze Scripts
    ############################################################

    - name: Upload Bronze Scripts to S3
      run: |
        aws s3 sync glue/bronze_to_silver \
          s3://${{ secrets.S3_BUCKET_NAME }}/glue/bronze_to_silver \
          --delete

    ############################################################
    # Upload Silver Scripts
    ############################################################

    - name: Upload Silver Scripts to S3
      run: |
        aws s3 sync glue/silver_to_gold \
          s3://${{ secrets.S3_BUCKET_NAME }}/glue/silver_to_gold \
          --delete
    ############################################################
    # Upload Crawler Scripts
    ############################################################

    - name: Upload Crawler Scripts to S3
      run: |
        aws s3 sync glue/crawler \
          s3://${{ secrets.S3_BUCKET_NAME }}/glue/crawler \
          --delete

    ############################################################
    # Upload Athena SQL Files
    ############################################################

    - name: Upload Athena SQL Files
      run: |
        aws s3 sync athena/sql \
          s3://${{ secrets.GOLD_BUCKET_NAME }}/athena/sql \
          --delete

    ############################################################
    # Verify Athena SQL Upload
    ############################################################

    - name: Verify Athena SQL Upload
      run: |
        aws s3 ls s3://${{ secrets.GOLD_BUCKET_NAME }}/athena/sql/

    ############################################################
    # Terraform
    ############################################################

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Format Check
      working-directory: terraform
      run: terraform fmt -check

    - name: Terraform Validate
      working-directory: terraform
      run: terraform validate

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve tfplan

    ############################################################
    # Trigger Glue Workflow
    ############################################################

    - name: Trigger Glue Workflow
      run: |
        RUN_ID=$(aws glue start-workflow-run \
          --name flight-delay-workflow \
          --query "RunId" \
          --output text)

        echo "Workflow Run ID: $RUN_ID"

        echo "WORKFLOW_RUN_ID=$RUN_ID" >> $GITHUB_ENV

    ############################################################
    # Wait for Glue Workflow to Complete
    ############################################################

    - name: Wait for Glue Workflow
      run: |
        echo "Waiting for Glue Workflow to complete..."

        while true
        do
          STATUS=$(aws glue get-workflow-run \
            --name flight-delay-workflow \
            --run-id "$WORKFLOW_RUN_ID" \
            --query "Run.Status" \
            --output text)

          echo "Workflow Status: $STATUS"

          if [ "$STATUS" = "COMPLETED" ]; then
            echo "Glue Workflow completed successfully."
            break
          fi

          if [ "$STATUS" = "ERROR" ] || \
             [ "$STATUS" = "STOPPED" ]; then
            echo "Glue Workflow failed."
            exit 1
          fi

          sleep 30
        done

    ############################################################
    # Verify Gold Output
    ############################################################

    - name: Verify Gold Output
      run: |
        echo "Checking Gold bucket..."

        for i in {1..12}
        do
          FILE_COUNT=$(aws s3 ls s3://${{ secrets.GOLD_BUCKET_NAME }}/Gold_Glue_Test/ --recursive | wc -l)

          echo "Attempt $i - Files Found: $FILE_COUNT"

          if [ "$FILE_COUNT" -gt 0 ]; then
            echo "Gold output verified successfully."
            exit 0
          fi

          echo "Waiting 10 seconds before checking again..."
          sleep 10
        done

        echo "Gold bucket is still empty after waiting."
        exit 1
    ############################################################
    # Run Glue Crawler
    ############################################################

    - name: Run Glue Crawler
      env:
        CRAWLER_NAME: flight-gold-crawler
      run: |
        python glue/crawler/crawler.py

    ############################################################
    # Execute Athena SQL
    ############################################################

    - name: Execute Athena SQL
      env:
        GOLD_BUCKET: ${{ secrets.GOLD_BUCKET_NAME }}
        ATHENA_DATABASE: flight_gold
        ATHENA_WORKGROUP: primary
      run: |
        python athena/athena.py



    ############################################################
    # Deployment Complete
    ############################################################

    - name: Deployment Complete
      run: |
        echo "======================================"
        echo "Flight Delay ETL Pipeline Completed!"
        echo "======================================"
